spring:
  application:
    name: library-design-pattern

    # Configuración H2 y R2DBC para ReactiveCrudRepository
    r2dbc:
        url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    h2:
        console:
            enabled: true
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
    sql:
        init:
            mode: always
            platform: h2
            schema-locations: classpath:schema.sql
            data-locations: classpath:data.sql
server:
    port: 8080